### ISSUE TITLE
CPU Usage[BUG]

### ISSUE THREAD

**Issue by Fluffy41** [Exiled-Team/DiscordIntegration#126] opened 2022-08-12 18:14 UTC
**Describe the bug**
Discord Integration is using to much CPU.
![image](https://user-images.githubusercontent.com/74478103/184417456-24bfccac-88b7-4834-b941-7bdadd4d2bc2.png)

**To Reproduce**
its while the Bot is running

**Expected behavior**
Not so much CPU Usage.
![image](https://user-images.githubusercontent.com/74478103/184417468-8d680b52-758f-4999-a2cb-0ca1f72dcf65.png)

**Server logs**
Please include a pastebin of your localadmin log file (or both MA_log and SCP_log files if you use MultiAdmin) from the time in which the bug occured
https://pastebin.com/SMsN6srA

**EXILED Version ("latest" is not a version):**
5.2.2

**Results of `show plugins` command in console:**
[20:05:51] Total number of plugins: 20                                                                                                                                                                   
Enabled plugins: 20         
Disabled plugins: 0                       
                                                  
CedMod:                              
        - Author: ced777ric#8321
        - Version: 3.1.3            
        - Required Exiled Version: 5.0.0
        - Prefix: cm                    
        - Priority: Highest             
Exiled.Events:               
        - Author: Exiled Team
        - Version: 5.2.2.0          
        - Required Exiled Version: 5.2.2.0
        - Prefix: exiled_events         
        - Priority: Highest             
RainbowLobby:              
        - Author: Jesus-QC
        - Version: 1.0.1.2                                                                                                                                                                                
        - Required Exiled Version: 5.0.0                                                                                                                                                                  
        - Prefix: RainbowLobby                                                                                                                                                                            
        - Priority: Medium                                                                                                                                                                                
Spectator Shooting Range:
        - Author: rayzer                                                                                                                                                                                
        - Version: 3.0.1     
        - Required Exiled Version: 5.2.1
        - Prefix: spectator_shooting_range
        - Priority: Medium           
Exiled.CustomRoles:       
        - Author: Exiled Team
        - Version: 5.2.2.0  
        - Required Exiled Version: 5.2.2.0
        - Prefix: exiled_custom_roles   
        - Priority: Medium
WaitAndChillReborn:       
        - Author: Michal78900
        - Version: 5.0.1    
        - Required Exiled Version: 5.2.1
        - Prefix: wait_and_chill_reborn 
        - Priority: Medium         
WhoAreMyTeammates:        
        - Author: XoMiya-WPC & TheUltiOne
        - Version: 4.0.3                                                                             
        - Required Exiled Version: 4.2.3
        - Prefix: WhoAreMyTeammates       
        - Priority: Medium      
RespawnTimer:             
        - Author: Michal78900
        - Version: 3.1.0            
        - Required Exiled Version: 5.0.0
        - Prefix: respawn_timer         
        - Priority: Medium   
Exiled.Updater:           
        - Author: Exiled.Updater
        - Version: 3.1.1.0  
        - Required Exiled Version: 5.2.2.0
        - Prefix: exiled_updater        
        - Priority: Medium           
DiscordIntegration:       
        - Author: DiscordIntegration
        - Version: 6.0.3.0
        - Required Exiled Version: 5.2.0
        - Prefix: discord_integration   
        - Priority: Medium   
Stalky106:                
        - Author: RogerFK && Raul125
        - Version: 3.3.2       
        - Required Exiled Version: 5.0.0
        - Prefix: ST106                 
        - Priority: Medium 
Exiled.Permissions:       
        - Author: Exiled Team                                                                                                                                                                             
        - Version: 5.2.2.0                                                                                                                                                                                
        - Required Exiled Version: 5.2.2.0                                                                                                                                                                
        - Prefix: exiled_permissions                                                                                                                                                                      
        - Priority: Medium 
Exiled.CustomItems:                                                                                                                                                                               
        - Author: Exiled Team
        - Version: 5.2.2.0              
        - Required Exiled Version: 5.2.2.0
        - Prefix: exiled_custom_items
        - Priority: Medium
DoorRestartSystem:           
        - Author: GameKuchen
        - Version: 3.4.0                  
        - Required Exiled Version: 5.0.0
        - Prefix: DRS     
        - Priority: Medium
ElevatorLockdown:            
        - Author: Marco15453
        - Version: 1.8.0                
        - Required Exiled Version: 3.0.0
        - Prefix: elevator_lockdown
        - Priority: Medium
Exiled.CreditTags:                       
        - Author: Babyboucher20 & iRebbok & Exiled Team                                              
        - Version: 5.2.2.0              
        - Required Exiled Version: 5.2.2.0
        - Prefix: exiled_credits
        - Priority: Medium
SCPUtils:                    
        - Author: Terminator_97#0507
        - Version: 4.0.1                
        - Required Exiled Version: 5.0.0
        - Prefix: s_c_p_utils
        - Priority: Medium
Suicide - Pro Edition:          
        - Author: TheUltiOne
        - Version: 2.1.1                  
        - Required Exiled Version: 5.1.0
        - Prefix: suicide_pro_edition
        - Priority: Medium
CoinTweaks:                         
        - Author: GabiRP  
        - Version: 1.0.8                
        - Required Exiled Version: 4.0.0
        - Prefix: coin_tweaks
        - Priority: Medium
SCPStats:                           
        - Author: PintTheDragon
        - Version: 1.5.4                
        - Required Exiled Version: 5.2.2
        - Prefix: scp_stats
        - Priority: Lowest

**Additional context**

**Comment by joker-119** [comment] 2022-08-15 12:27
This is likely caused because 0 is not a valid channel ID, or an invalid GuildID: 0. If the GuildID is correct, to avoid this error, disabling the logging of events targeting channels that you've purposefully set to an invalid channel ID.

Also duplicate of #124

**Closed by joker-119** 2022-08-15 12:27 UTC
