### ISSUE TITLE
[BUG] Player count not showing

### ISSUE THREAD

**Issue by Zenlet** [Exiled-Team/DiscordIntegration#92] opened 2022-06-06 19:17 UTC
**Describe the bug**
The status of the bot does not display the correct player count but yet still shows that the server is active via online status

**To Reproduce**
No reproducing, just happens

**Expected behavior**
The bot shows the correct player count from the official SCPSL Server list.

**EXILED Version ("latest" is not a version):**
5.1.1

**Additional context**
![2khnXnaDuO](https://user-images.githubusercontent.com/62112167/172231452-0c17e58a-5951-48e1-adbd-7afd73edb316.png)
![CAM3kJc8qD](https://user-images.githubusercontent.com/62112167/172231453-d883c608-bead-412c-8eac-06e47bcb2a07.png)

**Comment by joker-119** [comment] 2022-06-06 19:49
Duplicate of #91

**Closed by joker-119** 2022-06-06 19:49 UTC
